name: app_surveyor
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  dotted_border: ^2.1.0
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.0.13
  table_calendar: ^3.1.2
  google_maps_flutter: ^2.7.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/logo_crossnet.png
    - lib/images/foto.png
    - lib/images/dummy.jpeg
