name: app_user
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.9.0
  http: ^1.2.2
  image_picker: ^1.1.2
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/logo_crossnet.png
    - lib/images/foto.png
    - lib/images/dummy.jpeg
